name = "shortener"
main = "src/app.ts"
compatibility_date = "2024-10-04"

routes = [{ pattern = "a-ma.zip", custom_domain = true }]

assets = { directory = "./www/", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "url-shortner-db"
database_id = "83e2a789-0639-4e3b-b2e3-545deb75a421"

[[kv_namespaces]]
binding = "CACHE"
id = "984436f7bb5f413fb972b97d982e3e84"
